---
- name: Make directory for wp-cli
  file: path=/srv/php/wp-cli state=directory owner=wordpress group=wordpress mode=0755 recurse=yes
  tags:
      - wp-setting

- name: Download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/srv/php/wp-cli
  tags:
      - wp-setting

- name: Rename wp-cli
  shell: mv /srv/php/wp-cli/wp-cli.phar /srv/php/wp-cli/wp
  tags:
      - wp-setting

- name: chmod wp-cli
  file: path=/srv/php/wp-cli/wp owner=wordpress group=wordpress mode=0755
  tags:
      - wp-setting


- name: Wordpress Core Install
  become: yes
  become_user: wordpress
  shell: /srv/php/wp-cli/wp core install --url={{wp_url}} --title={{wp_site_title}} --admin_user={{wp_admin_user}} --admin_password={{wp_admin_pass}} --admin_email={{wp_admin_email}}
  tags:
      - wp-setting

- name: Set Language
  become: yes
  become_user: wordpress
  shell: /srv/php/wp-cli/wp core language install ja --activate
  tags:
      - wp-setting

- name: Worpress Theme Install
  become: yes
  become_user: wordpress
  shell: /srv/php/wp-cli/wp theme install twentyfourteen --activate
  tags:
      - wp-setting
